engines:
  haxe-checkstyle:
    enabled: true
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
exclude_paths:
  - "data/**.hx"
ratings:
  paths:
    - "src/**.hx"
    - "**.md"
