language: haxe

sudo: false

dist: trusty

addons:
  apt:
    packages:
    - zlib1g
    - libpcre3

haxe:
  - "3.4.2"
  - development

install:
  # Extension dependencies
  - haxelib install hxnodejs
  - haxelib install vscode
  - haxelib install jstack
  - haxelib install compiletime
  # HaxeUI dependencies
  - haxelib install hscript
  - haxelib git haxeui-core https://github.com/haxeui/haxeui-core.git
  - haxelib git haxeui-html5 https://github.com/haxeui/haxeui-html5.git

script:
  - haxe build.hxml
